version: '3.8'
services:
    postgres_db:
        image: postgres:latest
        container_name: PostgresContainer 
        restart: always
        env_file:
            - .env
        ports:
            - '5432:5432'
        volumes:
            - postgres_db:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - postgres-db-network
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'teste@teste.com'
            PGADMIN_DEFAULT_PASSWORD: 'teste'
        ports:
            - 16543:80
        volumes:
            - ./servers.json:/pgadmin4/servers.json
        networks:
            - postgres-db-network
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/project
        ports:
            - 8000:8000
        links:
            - postgres_db:postgres_db
        depends_on:
            - postgres_db
        env_file:
            - .env
        networks:
            - postgres-db-network
volumes:
    postgres_db:
#         driver: local
networks:
    postgres-db-network:
        driver: bridge