CREATE TABLE "appi_request" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "type" varchar(10) NOT NULL,
    "url" varchar(200) NOT NULL,
    "header" varchar(200),
    "body" varchar(200),
    "modified_at" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone NOT NULL
);

INSERT INTO "appi_request" ("type", "url", "header", "body", "modified_at", "created_at") VALUES ('GET','https://jsonplaceholder.typicode.com/posts','','',now(),now());

--CREATE INDEX "appi_request_index" ON "appi_request" ("id");